vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/public/img'

            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true
